MinMax_U_disp: &id001 !!python/tuple
- -30
- 30
MinMax_V_disp: *id001
ROI: full
correlation_method: circular
deformation_method: symmetric
do_sig2noise_validation: false
dt: 1
dynamic_masking_filter_size: 7
dynamic_masking_method: None
dynamic_masking_threshold: 0.005
extract_sig2noise: false
filepath_images: .
filter_kernel_size: 2
filter_method: localmean
frame_pattern_a: exp1_001_a.bmp
frame_pattern_b: exp1_001_b.bmp
interpolation_order: 3
iterations: 3
max_filter_iteration: 4
median_size: 1
median_threshold: 3
normalized_correlation: false
overlap: !!python/tuple
- 32
- 16
- 8
replace_vectors: true
save_folder_suffix: Test_4
save_path: ./res
save_plot: true
scale_plot: 100
scaling_factor: 1
show_plot: true
sig2noise_mask: 2
sig2noise_method: peak2peak
sig2noise_threshold: 1.05
smoothn: true
smoothn_p: 0.5
std_threshold: 10
subpixel_method: gaussian
validation_first_pass: true
windowsizes: !!python/tuple
- 64
- 32
- 16
